server:
 port: 8081
 servlet:
  context-path: /jpa
  
spring:
 thymeleaf:
  cache: false
  mode: HTML
  encoding: UTF-8
 # DB 設定 
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/jpa2?serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true
  username: root
  password: 12345678
 # JPA 設定 
 jpa:
  database: MYSQL
  show-sql: true
  hibernate:
   ddl-auto: update
  # 啟動可以使用 hibernate sql
  properties:
   hibernate:
     dialect: org.hibernate.dialect.MySQL5Dialect
     format_sql: true
